dependencies:
  - python=3.8.5
  - pip=20.2.2
  - pytorch=1.4.0
  - pandas=1.1.0
  - numpy=1.19.1
  - scipy=1.5.2
  - matplotlib-base=3.3.1
  - seaborn=0.10.1
  - jupyterlab=2.2.6
  - nb_conda=2.2.1
  - pip:
    - scanpy==1.6.0
